# Generated by Django 3.2.4 on 2021-09-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasic',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('userFirstName', models.CharField(max_length=100)),
                ('userLastName', models.CharField(max_length=100)),
                ('userAddress', models.CharField(max_length=200)),
                ('userVillage', models.CharField(max_length=200)),
                ('userTaluka', models.CharField(max_length=200)),
                ('userDistrict', models.CharField(max_length=200)),
                ('userContact', models.IntegerField(unique=True)),
                ('userEmail', models.EmailField(max_length=200, unique=True)),
                ('userPassword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserWellRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userWellID', models.CharField(max_length=200, null=True)),
                ('userWellType', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.userbasic')),
            ],
        ),
        migrations.CreateModel(
            name='UserWaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.userbasic')),
                ('userWellID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.userwellregistration')),
            ],
        ),
        migrations.CreateModel(
            name='UserOtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTotalFamilyMembers', models.IntegerField(null=True)),
                ('userAdultFamMembers', models.IntegerField(null=True)),
                ('userChildrenFamMembers', models.IntegerField(null=True)),
                ('userAreaOfLandOwned', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.userbasic')),
            ],
            options={
                'verbose_name_plural': 'Other User Info',
            },
        ),
    ]
