# Generated by Django 3.2.4 on 2021-09-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwapp', '0002_auto_20210917_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RechargeStructures',
        ),
    ]
