# Generated by Django 3.2.4 on 2021-09-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwapp', '0003_delete_rechargestructures'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeStructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechargeStructID', models.CharField(max_length=50, unique=True)),
                ('rechargeStructBuiltDate', models.DateField()),
                ('rechargeStructOwnership', models.CharField(max_length=50)),
                ('rechargeStructVolumePotential', models.DecimalField(decimal_places=3, max_digits=20)),
                ('rechargeStructVolumeRecharged', models.DecimalField(decimal_places=3, max_digits=20)),
                ('villageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.village')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeStructuresPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechargeStructDateOfInput', models.DateField()),
                ('rechargeStructVolumeRecharged', models.DecimalField(decimal_places=3, max_digits=20)),
                ('rechargeStructID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.rechargestructures')),
                ('villageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwapp.village')),
            ],
        ),
    ]
