# Generated by Django 3.2.4 on 2021-09-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwapp', '0003_userwellregistration_userwelllocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwellregistration',
            name='userWelllocation',
        ),
    ]
