# Generated by Django 3.2.4 on 2021-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwapp', '0004_rechargestructures_rechargestructuresprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorewellsYedshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location_lat', models.DecimalField(decimal_places=5, max_digits=20)),
                ('location_long', models.DecimalField(decimal_places=5, max_digits=20)),
                ('location_altitude', models.DecimalField(decimal_places=5, max_digits=20)),
                ('location_precision', models.DecimalField(decimal_places=5, max_digits=20)),
                ('address', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('useTime', models.IntegerField()),
                ('borewellFoot', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Borewells Yedshi',
            },
        ),
    ]
